simType='sym_file'
symProps=[{'name': 'p1', 
'RBs': [{'pred_name': 'biter', 
		'pred_sem': [[u'e1',0.0],
                     [u'e2',0.0]],
		'higher_order': False, 
		'object_name': 'dogs', 
		'object_sem': [[u'e1',.92],
					   [u'e2',.38]],
		'P': 'nil'}, 
		{'pred_name': 'bitten', 
		'pred_sem': [[u'e1',.5],
					 [u'e2',.88]],
		'higher_order': False, 
		'object_name': 'cats', 
		'object_sem': [[u'e1',.19],
					   [u'e2',.98]],
		'P': 'nil'}], 
		'set': 'driver', 'analog': 0},
{'name': 'p2',
'RBs': [{'pred_name': 'hunter', 
		'pred_sem': [[u'e1',0.0],
                     [u'e2',0.0]],
		'higher_order': False, 
		'object_name': 'lions', 
		'object_sem': [[u'e1',0.98],
					   [u'e2',0.19]],
		'P': 'nil'}, 
		{'pred_name': 'hunted', 
		'pred_sem': [[u'e1',0.6],
					 [u'e2',0.78]],
		'higher_order': False, 
		'object_name': 'deer', 
		'object_sem': [[u'e1',.38],
					   [u'e2',.92]],
		'P': 'nil'}], 
		'set': 'recipient', 'analog': 0},
{'name': 'p3',
'RBs': [{'pred_name': 'listener',
        'pred_sem': [[u'e1',1.0],
                     [u'e2',0.0]],
          'higher_order': False,
          'object_name': 'me',
        'object_sem': [[u'e1',.7],
                       [u'e2',.7]],
          'P': 'nil'},
          {'pred_name': 'speaker',
        'pred_sem': [[u'e1',0.0],
                     [u'e2',0.0]],
          'higher_order': False,
          'object_name': 'you',
        'object_sem': [[u'e1',0.0],
                       [u'e2',1.0]],
          'P': 'nil'}],
          'set': 'driver', 'analog': 0},
{'name': 'p4',
 'RBs':[{'pred_name': 'big',
        'pred_sem': [[u'e1',.1],
                     [u'e2',.9]],
          'higher_order': False,
          'object_name': 'dogs',
        'object_sem': [[u'e1',.92],
                       [u'e2',.38]],
          'P': 'nil'}],
 		'set':'recipient','analog':0}]







