simType='sym_file'
symProps=[{'name': 'p1', 
'RBs': [{'pred_name': 'biter', 
		'pred_sem': [[u'e1',1,u'e1',0,u'state'],
					 [u'e2',1,u'e2',0,u'state']],
		'higher_order': False, 
		'object_name': 'dogs', 
		'object_sem': [[u'e1',1,u'e1',.1,u'state'],
					   [u'e2',1,u'e2',.2,u'state']],
		'P': 'nil'}, 
		{'pred_name': 'bitten', 
		'pred_sem': [[u'e1',1,u'e1',.5,u'state'],
					 [u'e2',1,u'e2',.6,u'state']],
		'higher_order': False, 
		'object_name': 'cats', 
		'object_sem': [[u'e1',1,u'e1',.9,u'state'],
					   [u'e2',1,u'e2',.95,u'state']],
		'P': 'nil'}], 
		'set': 'driver', 'analog': 0},
{'name': 'p2', 
'RBs': [{'pred_name': 'hunter', 
		'pred_sem': [[u'e1',1,u'e1',0,u'state'],
					 [u'e2',1,u'e2',0,u'state']],
		'higher_order': False, 
		'object_name': 'lions', 
		'object_sem': [[u'e1',1,u'e1',0.2,u'state'],
					   [u'e2',1,u'e2',0.1,u'state']],
		'P': 'nil'}, 
		{'pred_name': 'hunted', 
		'pred_sem': [[u'e1',1,u'e1',0.6,u'state'],
					 [u'e2',1,u'e2',0.5,u'state']],
		'higher_order': False, 
		'object_name': 'deer', 
		'object_sem': [[u'e1',1,u'e1',.95,u'state'],
					   [u'e2',1,u'e2',.9,u'state']],
		'P': 'nil'}], 
		'set': 'recipient', 'analog': 0},
{'name': 'p3',
'RBs': [{'pred_name': 'listener',
        'pred_sem': [[u'e1',1,u'e1',0.6,u'state'],
                     [u'e2',1,u'e2',0.5,u'state']],
          'higher_order': False,
          'object_name': 'me',
        'object_sem': [[u'e1',1,u'e1',.95,u'state'],
                       [u'e2',1,u'e2',.9,u'state']],
          'P': 'nil'},
          {'pred_name': 'speaker',
        'pred_sem': [[u'e1',1,u'e1',0,u'state'],
                     [u'e2',1,u'e2',0,u'state']],
          'higher_order': False,
          'object_name': 'you',
        'object_sem': [[u'e1',1,u'e1',0.2,u'state'],
                       [u'e2',1,u'e2',0.1,u'value']],
          'P': 'nil'}],
          'set': 'recipient', 'analog': 0}]







